# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/refacedxlib.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(830, 600)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.midi_setup = QtWidgets.QFrame(self.centralwidget)
        self.midi_setup.setEnabled(True)
        self.midi_setup.setFrameShape(QtWidgets.QFrame.Box)
        self.midi_setup.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.midi_setup.setObjectName("midi_setup")
        self.midi_selectors = QtWidgets.QHBoxLayout(self.midi_setup)
        self.midi_selectors.setObjectName("midi_selectors")
        self.midiin_label = QtWidgets.QLabel(self.midi_setup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.midiin_label.sizePolicy().hasHeightForWidth())
        self.midiin_label.setSizePolicy(sizePolicy)
        self.midiin_label.setMidLineWidth(0)
        self.midiin_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.midiin_label.setObjectName("midiin_label")
        self.midi_selectors.addWidget(self.midiin_label)
        self.midiin_cb = QtWidgets.QComboBox(self.midi_setup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.midiin_cb.sizePolicy().hasHeightForWidth())
        self.midiin_cb.setSizePolicy(sizePolicy)
        self.midiin_cb.setMinimumContentsLength(25)
        self.midiin_cb.setObjectName("midiin_cb")
        self.midi_selectors.addWidget(self.midiin_cb)
        self.midiout_label = QtWidgets.QLabel(self.midi_setup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.midiout_label.sizePolicy().hasHeightForWidth())
        self.midiout_label.setSizePolicy(sizePolicy)
        self.midiout_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.midiout_label.setObjectName("midiout_label")
        self.midi_selectors.addWidget(self.midiout_label)
        self.midiout_cb = QtWidgets.QComboBox(self.midi_setup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.midiout_cb.sizePolicy().hasHeightForWidth())
        self.midiout_cb.setSizePolicy(sizePolicy)
        self.midiout_cb.setMinimumContentsLength(25)
        self.midiout_cb.setObjectName("midiout_cb")
        self.midi_selectors.addWidget(self.midiout_cb)
        self.verticalLayout.addWidget(self.midi_setup)
        self.tabbox_patchlists = QtWidgets.QTabWidget(self.centralwidget)
        self.tabbox_patchlists.setMinimumSize(QtCore.QSize(0, 0))
        self.tabbox_patchlists.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabbox_patchlists.setObjectName("tabbox_patchlists")
        self.tab_patches = QtWidgets.QWidget()
        self.tab_patches.setObjectName("tab_patches")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tab_patches)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.table_patches = QtWidgets.QTableView(self.tab_patches)
        self.table_patches.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.table_patches.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.table_patches.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.table_patches.setSortingEnabled(True)
        self.table_patches.setObjectName("table_patches")
        self.table_patches.horizontalHeader().setVisible(True)
        self.table_patches.horizontalHeader().setStretchLastSection(False)
        self.table_patches.verticalHeader().setVisible(False)
        self.horizontalLayout.addWidget(self.table_patches)
        self.tabbox_patchlists.addTab(self.tab_patches, "")
        self.tab_patchsets = QtWidgets.QWidget()
        self.tab_patchsets.setObjectName("tab_patchsets")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_patchsets)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.table_patchsets = QtWidgets.QTableView(self.tab_patchsets)
        self.table_patchsets.setObjectName("table_patchsets")
        self.verticalLayout_2.addWidget(self.table_patchsets)
        self.tabbox_patchlists.addTab(self.tab_patchsets, "")
        self.verticalLayout.addWidget(self.tabbox_patchlists)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 830, 29))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtWidgets.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        self.menu_Patch = QtWidgets.QMenu(self.menubar)
        self.menu_Patch.setObjectName("menu_Patch")
        MainWindow.setMenuBar(self.menubar)
        self.toolbar = QtWidgets.QToolBar(MainWindow)
        self.toolbar.setObjectName("toolbar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolbar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_quit = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("application-exit")
        self.action_quit.setIcon(icon)
        self.action_quit.setShortcutContext(QtCore.Qt.ApplicationShortcut)
        self.action_quit.setVisible(True)
        self.action_quit.setMenuRole(QtWidgets.QAction.QuitRole)
        self.action_quit.setShortcutVisibleInContextMenu(True)
        self.action_quit.setObjectName("action_quit")
        self.action_import = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("document-import")
        self.action_import.setIcon(icon)
        self.action_import.setObjectName("action_import")
        self.action_send = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("document-send")
        self.action_send.setIcon(icon)
        self.action_send.setIconVisibleInMenu(False)
        self.action_send.setObjectName("action_send")
        self.action_request = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("download")
        self.action_request.setIcon(icon)
        self.action_request.setObjectName("action_request")
        self.action_delete = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("delete")
        self.action_delete.setIcon(icon)
        self.action_delete.setObjectName("action_delete")
        self.action_open = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("document-open")
        self.action_open.setIcon(icon)
        self.action_open.setObjectName("action_open")
        self.action_midi = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("audio-card")
        self.action_midi.setIcon(icon)
        self.action_midi.setObjectName("action_midi")
        self.action_export = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("document-export")
        self.action_export.setIcon(icon)
        self.action_export.setObjectName("action_export")
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.action_open)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.action_quit)
        self.menu_Patch.addAction(self.action_import)
        self.menu_Patch.addAction(self.action_export)
        self.menu_Patch.addSeparator()
        self.menu_Patch.addAction(self.action_request)
        self.menu_Patch.addAction(self.action_send)
        self.menu_Patch.addSeparator()
        self.menu_Patch.addAction(self.action_delete)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Patch.menuAction())
        self.toolbar.addAction(self.action_import)
        self.toolbar.addAction(self.action_request)
        self.toolbar.addAction(self.action_send)
        self.toolbar.addSeparator()
        self.toolbar.addAction(self.action_midi)

        self.retranslateUi(MainWindow)
        self.tabbox_patchlists.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.midiin_label.setText(_translate("MainWindow", "MIDI Input:"))
        self.midiout_label.setText(_translate("MainWindow", "MIDI Output:"))
        self.tabbox_patchlists.setTabText(self.tabbox_patchlists.indexOf(self.tab_patches), _translate("MainWindow", "&Patches"))
        self.tabbox_patchlists.setTabText(self.tabbox_patchlists.indexOf(self.tab_patchsets), _translate("MainWindow", "Patch &Sets"))
        self.menu_File.setTitle(_translate("MainWindow", "&File"))
        self.menu_Patch.setTitle(_translate("MainWindow", "&Patch"))
        self.toolbar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.action_quit.setText(_translate("MainWindow", "&Quit"))
        self.action_quit.setIconText(_translate("MainWindow", "&Quit"))
        self.action_quit.setToolTip(_translate("MainWindow", "Exit application"))
        self.action_quit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.action_import.setText(_translate("MainWindow", "&Import Patch(es)..."))
        self.action_import.setToolTip(_translate("MainWindow", "Import patch(es) from SysEx file(s)"))
        self.action_import.setShortcut(_translate("MainWindow", "Ctrl+I"))
        self.action_send.setText(_translate("MainWindow", "&Send Patch(es)"))
        self.action_send.setToolTip(_translate("MainWindow", "Send selected patch to MIDI output"))
        self.action_send.setShortcut(_translate("MainWindow", "Space"))
        self.action_request.setText(_translate("MainWindow", "&Request Patch "))
        self.action_request.setToolTip(_translate("MainWindow", "Request and receive SysEx patch from Synthesizer"))
        self.action_request.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.action_delete.setText(_translate("MainWindow", "&Delete Patch(es)"))
        self.action_delete.setToolTip(_translate("MainWindow", "Delete selected patch(es) from database"))
        self.action_delete.setShortcut(_translate("MainWindow", "Del"))
        self.action_open.setText(_translate("MainWindow", "&Open patch database"))
        self.action_open.setToolTip(_translate("MainWindow", "Load patch database from file"))
        self.action_open.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.action_midi.setText(_translate("MainWindow", "MIDI Setup"))
        self.action_midi.setToolTip(_translate("MainWindow", "Show MIDI input and ouput port selection"))
        self.action_export.setText(_translate("MainWindow", "&Export Patch(es)..."))
        self.action_export.setToolTip(_translate("MainWindow", "Export Patch(es) to SysEx file(s)"))
        self.action_export.setShortcut(_translate("MainWindow", "Ctrl+S"))
