VERSION_MAJOR = 0
VERSION_MINOR = 1
VERSION_PATCHLEVEL = 0
VERSION_SUFFIX = 'a3'
VERSION_INFO = (VERSION_MAJOR, VERSION_MINOR, VERSION_PATCHLEVEL, VERSION_SUFFIX)
VERSION_STRING = "%s.%s.%s%s" % VERSION_INFO

__version__ = VERSION_STRING
